import { shoppingItem } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import ItemModal from "~/components/ItemModal";

import { api } from "~/utils/api";
import Item from "~/components/Item";

const Feed = () => {
  const [items, setItems] = useState<shoppingItem[]>([]);
  const { data: itemsData, isLoading } = api.itemRouter.getAllItems.useQuery();

  if (isLoading || !itemsData) return <div>Loading...</div>;

  return (
    <ul className="mt-4 space-y-3">
      {itemsData.map((item) => {
        const { id } = item;
        return (
          <Item item={item} key={item.id} setItems={setItems} id={id}/>
        );
      })}
    </ul>
  );
};

const Home: NextPage = () => {
  const [modalOpen, setModalOpen] = useState<boolean>(false);

  api.itemRouter.getAllItems.useQuery();

  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {modalOpen && (
        <ItemModal setModalOpen={setModalOpen} />
      )}

      <main className="mx-auto my-12 max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-3xl font-semibold">My Shopping List</h2>
          <button
            type="button"
            className="rounded-md bg-blue-500 p-2 text-white text-lg transition duration-300 hover:bg-blue-600"
            onClick={() => setModalOpen(true)}
          >
            Add Shopping Item
          </button>
        </div>

        <Feed />
      </main>
    </>
  );
};

export default Home;
