import { shoppingItem } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import ItemModal from "~/components/ItemModal";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [items, setItems] = useState<shoppingItem[]>([]);
  const [modalOpen, setModalOpen] = useState<boolean>(false);

  const {} = api.itemRouter.addItem.useMutation({
    onSuccess: (item) => {
      setItems((prev) => [...prev, item]);
    },
  });

  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {modalOpen && <ItemModal setModalOpen={setModalOpen} setItems={setItems} />}

      <main className="mx-auto my-12 max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My Shopping List</h2>
          <button
            type="button"
            className="rounded-md bg-blue-500 p-2 text-white transition duration-300 hover:bg-blue-600"
            onClick={() => setModalOpen(true)}
          >
            Add Shopping Item
          </button>
        </div>

        <ul className="mt-4">
          {items.map((item) => (
            <li className="flex items-center justify-center" key={item.id}>
              <span>{item.name}</span>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
